export const serializeTask = (task) => ({
  id: String(task._id),
  parentTask: task.parentTask ? String(task.parentTask) : null,
  lifecycle: task.lifecycle ?? 'active',
  title: task.title,
  assignee: task.assignee ? String(task.assignee) : null,
  project: task.project,
  projectId: task.projectId ? String(task.projectId) : undefined,
  description: task.description,
  notes: task.notes ?? '',
  links: (task.links ?? []).map(({ label, url }) => ({ label, url })),
  priority: task.priority,
  estimateMinutes: task.estimateMinutes ?? 0,
  durationDays: task.durationDays ?? 1,
  status: task.status,
  blockerReason: task.blockerReason ?? '',
  due: task.due,
  recurrence: task.recurrence ?? 'none',
  repeatDay: task.repeatDay,
  repeatSource: task.repeatSource ? String(task.repeatSource) : undefined,
  createdAt: task.createdAt,
  updatedAt: task.updatedAt,
  checklist: (task.checklist ?? []).map((item) => ({
    id: item.id,
    text: item.text,
    done: item.done,
  })),
});
